# Перечесление всех игровых состояний/стадий


INTRO = 0
PLAYER_LETTER_CHOICE = 1
ANSWER_SHOWCASE = 2
PLAYER_QUESTION_CHOICE = 3
AI_QUESTION_CHOICE = 4
WAITING_FOR_ANSWER = 5
WAITING_FOR_AUDIO_SOURCE = 6
LOADING_QUESTION = 7
QUESTION_PREPARE = 8
AI_ANSWER = 9
PAUSE = 10
